services:
  oracle:
    image: kava/kava-tools:someting
    environment:
      CHAIN_ID: "kava-localnet"
      # REST endpoint
      LCD_URL: "http://kavanode:1317"
      # Cron tab for how frequently prices will be posted (ex: 1 minute)
      CRONTAB: "* * * * *"
      # bip39 mnemonic of oracle
      MNEMONIC: "desert october mammal tuition illness album engine solid enjoy harvest symptom rely camera unable okay avocado actual oppose remember lady dove canal argue cave"
      # List of markets the oracle will post prices for. See pricefeed parameters for the list of active markets.
      MARKET_IDS: "bnb:usd,bnb:usd:30"
      # percentage deviation from previous price needed to trigger a new price - (example 0.5%)
      DEVIATION: "0.005"
      # how long (in seconds) each price will remain valid - this value should be equal to the amount of time it takes for you to respond to a server outage (example 4 hours )
      EXPIRY: "14400"
      # how long (in seconds) before the oracle will consider a price expiring and post a new price, regardless of the value of deviation.
      # for example, if this is set to 600, the oracle will post a price any time the current posted price is expiring in less than 600 seconds.
      EXPIRY_THRESHOLD: "300"
      # if the oracle should use the legacy HD path for kava (118). Setting to "true" will use 118, false will use 459
      LEGACY_HD_PATH: "false"
