version: '3'
services:
    gethnode:
        image: "ethereum/client-go:latest"
        ports:
            # Non-default ports (+10) to not conflict with Kava EVM ports
            # HTTP JSON-RPC port
            - "8555:8545"
            # WS-RPC port
            - "8556:8546"
        volumes:
            - "./geth/initstate/.geth/keystore:/root/.ethereum/keystore"
            - "./geth/initstate/exported_state:/root/exported_state"
            - "./geth/initstate/eth-password:/root/eth-password"
            - "./geth/initstate/genesis.json:/root/genesis.json"
            - "./geth/initstate/entrypoint.sh:/entrypoint.sh"
        entrypoint: ["/bin/sh"]
        command: /entrypoint.sh
