version: '3'

services:
    kavanode:
        image: "kava/kava:v0.10.0"
        ports:
            # open default kava rpc port
            - "26657:26657"
        volumes:
            - "./initstate/.kvd:/root/.kvd"
        # start the blockchain, and set rpc to listen to connections from outside the container
        command: ["kvd", "start", "--pruning=nothing" ,"--rpc.laddr=tcp://0.0.0.0:26657"]
    kavarest:
        image: "kava/kava:v0.10.0"
        ports:
            # open default rest port
            - "1317:1317"
        command: ["kvcli", "rest-server", "--node=tcp://kavanode:26657", "--trust-node", "--laddr=tcp://0.0.0.0:1317"]
