services:
    kavanode:
        image: "kava/kava:${KAVA_TAG:-v0.26.0-goleveldb}"
        ports:
            # open default kava rpc port
            - "26657:26657"
            # open rest port
            - "1317:1317"
            # open grpc port
            - "9090:9090"
            # open grpc-web port
            - "9091:9091"
            # open EVM JSON-RPC port
            - "8545:8545"
            # open Eth websocket port
            - "8546:8546"
        volumes:
            - "./kava/initstate/.kava:/root/.kava"
        # start the blockchain, and set rpc to listen to connections from outside the container
        command:
            - "sh"
            - "-c"
            - "/root/.kava/config/init-data-directory.sh && kava start --rpc.laddr=tcp://0.0.0.0:26657"
        healthcheck:
            test: [
                "CMD",
                "curl",
                "-f",
                "-X",
                "POST",
                "-H",
                "Content-Type: application/json",
                "http://localhost:8545",
            ]
            interval: 30s
            timeout: 30s
            start_period: 1m
            start_interval: 5s
            retries: 3
