version: '3'
services:
  kava:
    image: "kava/kava:${KAVA_IMAGE_TAG:-master}"
    volumes:
      - "./kava-2:/root/.kava"
    # start the blockchain, and set rpc to listen to connections from outside the container
    command:
      - "sh"
      - "-c"
      - "/root/.kava/config/init-data-directory.sh && kava start --rpc.laddr=tcp://0.0.0.0:26657 --fast_sync=false --p2p.pex=false --log_level=debug"
