version: '3'
services:
  kava-1:
    image: "kava/kava:local"
    ports:
      # open default kava rpc port
      - "26657:26657"
      # open rest port
      - "1317:1317"
      # open grpc port
      - "9090:9090"
      # open grpc-web port
      - "9091:9091"
      # open EVM JSON-RPC port
      - "8545:8545"
      # open Eth websocket port
      - "8546:8546"
    volumes:
      - "./kava-1/config:/root/.kava/config"
    # start the blockchain, and set rpc to listen to connections from outside the container
    command:
      - "sh"
      - "-c"
      - "/root/.kava/config/init-data-directory.sh && kava start --rpc.laddr=tcp://0.0.0.0:26657"
  kava-2:
    image: "kava/kava:local"
    # ports for 2nd node are same as above + 100
    ports:
      # open default kava rpc port
      - "26757:26657"
      # open rest port
      - "1417:1317"
      # open grpc port
      - "9190:9090"
      # open grpc-web port
      - "9191:9091"
      # open EVM JSON-RPC port
      - "8645:8545"
      # open Eth websocket port
      - "8646:8546"
    volumes:
      - "./kava-2/config:/root/.kava/config"
    # start the blockchain, and set rpc to listen to connections from outside the container
    command:
      - "sh"
      - "-c"
      - "/root/.kava/config/init-data-directory.sh && kava start --rpc.laddr=tcp://0.0.0.0:26657"
