version: '3'
services:
  kava-1:
    extends:
      file: docker-compose.template.yml
      service: kava
    ports:
      # open default kava rpc port
      - "26657:26657"
      # open rest port
      - "1317:1317"
      # open grpc port
      - "9090:9090"
      # open grpc-web port
      - "9091:9091"
      # open EVM JSON-RPC port
      - "8545:8545"
      # open Eth websocket port
      - "8546:8546"
    volumes:
      - "./kava-1:/root/.kava"
  kava-2:
    extends:
      file: docker-compose.template.yml
      service: kava
    volumes:
      - "./kava-2:/root/.kava"
  kava-3:
    extends:
      file: docker-compose.template.yml
      service: kava
    volumes:
      - "./kava-3:/root/.kava"
  kava-4:
    extends:
      file: docker-compose.template.yml
      service: kava
    volumes:
      - "./kava-4:/root/.kava"
  kava-5:
    extends:
      file: docker-compose.template.yml
      service: kava
    volumes:
      - "./kava-5:/root/.kava"
  kava-6:
    extends:
      file: docker-compose.template.yml
      service: kava
    volumes:
      - "./kava-6:/root/.kava"
  kava-7:
    extends:
      file: docker-compose.template.yml
      service: kava
    volumes:
      - "./kava-7:/root/.kava"
  kava-8:
    extends:
      file: docker-compose.template.yml
      service: kava
    volumes:
      - "./kava-8:/root/.kava"
  kava-9:
    extends:
      file: docker-compose.template.yml
      service: kava
    volumes:
      - "./kava-9:/root/.kava"
  kava-10:
    extends:
      file: docker-compose.template.yml
      service: kava
    volumes:
      - "./kava-10:/root/.kava"
  kava-11:
    extends:
      file: docker-compose.template.yml
      service: kava
    volumes:
      - "./kava-11:/root/.kava"
  kava-12:
    extends:
      file: docker-compose.template.yml
      service: kava
    volumes:
      - "./kava-11:/root/.kava"
  kava-13:
    extends:
      file: docker-compose.template.yml
      service: kava
    volumes:
      - "./kava-11:/root/.kava"
