version: '3'
services:
  kava-1:
    image: "kava/kava:${KAVA_IMAGE_TAG:-master}"
    ports:
      # open default kava rpc port
      - "26657:26657"
      # open rest port
      - "1317:1317"
      # open grpc port
      - "9090:9090"
      # open grpc-web port
      - "9091:9091"
      # open EVM JSON-RPC port
      - "8545:8545"
      # open Eth websocket port
      - "8546:8546"
    volumes:
      - "./kava-1:/root/.kava"
    # start the blockchain, and set rpc to listen to connections from outside the container
    command:
      - "sh"
      - "-c"
      - "/root/.kava/config/init-data-directory.sh && kava start --rpc.laddr=tcp://0.0.0.0:26657"
  kava-2:
    image: "kava/kava:${KAVA_IMAGE_TAG:-master}"
    volumes:
      - "./kava-2:/root/.kava"
    # start the blockchain, and set rpc to listen to connections from outside the container
    command:
      - "sh"
      - "-c"
      - "/root/.kava/config/init-data-directory.sh && kava start --rpc.laddr=tcp://0.0.0.0:26657"
  kava-3:
    image: "kava/kava:${KAVA_IMAGE_TAG:-master}"
    volumes:
      - "./kava-3:/root/.kava"
    # start the blockchain, and set rpc to listen to connections from outside the container
    command:
      - "sh"
      - "-c"
      - "/root/.kava/config/init-data-directory.sh && kava start --rpc.laddr=tcp://0.0.0.0:26657"
  kava-4:
    image: "kava/kava:${KAVA_IMAGE_TAG:-master}"
    volumes:
      - "./kava-4:/root/.kava"
    # start the blockchain, and set rpc to listen to connections from outside the container
    command:
      - "sh"
      - "-c"
      - "/root/.kava/config/init-data-directory.sh && kava start --rpc.laddr=tcp://0.0.0.0:26657"
  kava-5:
    image: "kava/kava:${KAVA_IMAGE_TAG:-master}"
    volumes:
      - "./kava-5:/root/.kava"
    # start the blockchain, and set rpc to listen to connections from outside the container
    command:
      - "sh"
      - "-c"
      - "/root/.kava/config/init-data-directory.sh && kava start --rpc.laddr=tcp://0.0.0.0:26657"
  kava-6:
    image: "kava/kava:${KAVA_IMAGE_TAG:-master}"
    volumes:
      - "./kava-6:/root/.kava"
    # start the blockchain, and set rpc to listen to connections from outside the container
    command:
      - "sh"
      - "-c"
      - "/root/.kava/config/init-data-directory.sh && kava start --rpc.laddr=tcp://0.0.0.0:26657"
  kava-7:
    image: "kava/kava:${KAVA_IMAGE_TAG:-master}"
    volumes:
      - "./kava-7:/root/.kava"
    # start the blockchain, and set rpc to listen to connections from outside the container
    command:
      - "sh"
      - "-c"
      - "/root/.kava/config/init-data-directory.sh && kava start --rpc.laddr=tcp://0.0.0.0:26657"
  kava-8:
    image: "kava/kava:${KAVA_IMAGE_TAG:-master}"
    volumes:
      - "./kava-8:/root/.kava"
    # start the blockchain, and set rpc to listen to connections from outside the container
    command:
      - "sh"
      - "-c"
      - "/root/.kava/config/init-data-directory.sh && kava start --rpc.laddr=tcp://0.0.0.0:26657"
  kava-9:
    image: "kava/kava:${KAVA_IMAGE_TAG:-master}"
    volumes:
      - "./kava-9:/root/.kava"
    # start the blockchain, and set rpc to listen to connections from outside the container
    command:
      - "sh"
      - "-c"
      - "/root/.kava/config/init-data-directory.sh && kava start --rpc.laddr=tcp://0.0.0.0:26657"
  kava-10:
    image: "kava/kava:${KAVA_IMAGE_TAG:-master}"
    volumes:
      - "./kava-10:/root/.kava"
    # start the blockchain, and set rpc to listen to connections from outside the container
    command:
      - "sh"
      - "-c"
      - "/root/.kava/config/init-data-directory.sh && kava start --rpc.laddr=tcp://0.0.0.0:26657"
  kava-11:
    image: "kava/kava:${KAVA_IMAGE_TAG:-master}"
    volumes:
      - "./kava-11:/root/.kava"
    # start the blockchain, and set rpc to listen to connections from outside the container
    command:
      - "sh"
      - "-c"
      - "/root/.kava/config/init-data-directory.sh && kava start --rpc.laddr=tcp://0.0.0.0:26657"
  kava-12:
    image: "kava/kava:${KAVA_IMAGE_TAG:-master}"
    volumes:
      - "./kava-12:/root/.kava"
    # start the blockchain, and set rpc to listen to connections from outside the container
    command:
      - "sh"
      - "-c"
      - "/root/.kava/config/init-data-directory.sh && kava start --rpc.laddr=tcp://0.0.0.0:26657"
  kava-13:
    image: "kava/kava:${KAVA_IMAGE_TAG:-master}"
    volumes:
      - "./kava-13:/root/.kava"
    # start the blockchain, and set rpc to listen to connections from outside the container
    command:
      - "sh"
      - "-c"
      - "/root/.kava/config/init-data-directory.sh && kava start --rpc.laddr=tcp://0.0.0.0:26657"
