version: '3'
services:
  kava-1:
    image: "kava/kava:${KAVA_IMAGE_TAG:-master}"
    ports:
      # open default kava rpc port
      - "26657:26657"
      # open rest port
      - "1317:1317"
      # open grpc port
      - "9090:9090"
      # open grpc-web port
      - "9091:9091"
      # open EVM JSON-RPC port
      - "8545:8545"
      # open Eth websocket port
      - "8546:8546"
    volumes:
      - "./kava-1/config:/root/.kava/config"
    # start the blockchain, and set rpc to listen to connections from outside the container
    command:
      - "sh"
      - "-c"
      - "/root/.kava/config/init-data-directory.sh && kava start --rpc.laddr=tcp://0.0.0.0:26657"
  kava-2:
    image: "kava/kava:${KAVA_IMAGE_TAG:-master}"
    volumes:
      - "./kava-2/config:/root/.kava/config"
    # start the blockchain, and set rpc to listen to connections from outside the container
    command:
      - "sh"
      - "-c"
      - "/root/.kava/config/init-data-directory.sh && kava start --rpc.laddr=tcp://0.0.0.0:26657"
  kava-3:
    image: "kava/kava:${KAVA_IMAGE_TAG:-master}"
    volumes:
      - "./kava-3/config:/root/.kava/config"
    # start the blockchain, and set rpc to listen to connections from outside the container
    command:
      - "sh"
      - "-c"
      - "/root/.kava/config/init-data-directory.sh && kava start --rpc.laddr=tcp://0.0.0.0:26657"
  kava-4:
    image: "kava/kava:${KAVA_IMAGE_TAG:-master}"
    volumes:
      - "./kava-4/config:/root/.kava/config"
    # start the blockchain, and set rpc to listen to connections from outside the container
    command:
      - "sh"
      - "-c"
      - "/root/.kava/config/init-data-directory.sh && kava start --rpc.laddr=tcp://0.0.0.0:26657"
  kava-4:
    image: "kava/kava:${KAVA_IMAGE_TAG:-master}"
    volumes:
      - "./kava-4/config:/root/.kava/config"
    # start the blockchain, and set rpc to listen to connections from outside the container
    command:
      - "sh"
      - "-c"
      - "/root/.kava/config/init-data-directory.sh && kava start --rpc.laddr=tcp://0.0.0.0:26657"
  kava-5:
    image: "kava/kava:${KAVA_IMAGE_TAG:-master}"
    volumes:
      - "./kava-5/config:/root/.kava/config"
    # start the blockchain, and set rpc to listen to connections from outside the container
    command:
      - "sh"
      - "-c"
      - "/root/.kava/config/init-data-directory.sh && kava start --rpc.laddr=tcp://0.0.0.0:26657"
  kava-6:
    image: "kava/kava:${KAVA_IMAGE_TAG:-master}"
    volumes:
      - "./kava-6/config:/root/.kava/config"
    # start the blockchain, and set rpc to listen to connections from outside the container
    command:
      - "sh"
      - "-c"
      - "/root/.kava/config/init-data-directory.sh && kava start --rpc.laddr=tcp://0.0.0.0:26657"
  kava-7:
    image: "kava/kava:${KAVA_IMAGE_TAG:-master}"
    volumes:
      - "./kava-7/config:/root/.kava/config"
    # start the blockchain, and set rpc to listen to connections from outside the container
    command:
      - "sh"
      - "-c"
      - "/root/.kava/config/init-data-directory.sh && kava start --rpc.laddr=tcp://0.0.0.0:26657"
  kava-8:
    image: "kava/kava:${KAVA_IMAGE_TAG:-master}"
    volumes:
      - "./kava-8/config:/root/.kava/config"
    # start the blockchain, and set rpc to listen to connections from outside the container
    command:
      - "sh"
      - "-c"
      - "/root/.kava/config/init-data-directory.sh && kava start --rpc.laddr=tcp://0.0.0.0:26657"
  kava-9:
    image: "kava/kava:${KAVA_IMAGE_TAG:-master}"
    volumes:
      - "./kava-9/config:/root/.kava/config"
    # start the blockchain, and set rpc to listen to connections from outside the container
    command:
      - "sh"
      - "-c"
      - "/root/.kava/config/init-data-directory.sh && kava start --rpc.laddr=tcp://0.0.0.0:26657"
  kava-10:
    image: "kava/kava:${KAVA_IMAGE_TAG:-master}"
    volumes:
      - "./kava-10/config:/root/.kava/config"
    # start the blockchain, and set rpc to listen to connections from outside the container
    command:
      - "sh"
      - "-c"
      - "/root/.kava/config/init-data-directory.sh && kava start --rpc.laddr=tcp://0.0.0.0:26657"
