version: '3'
services:
    kava-pruning:
        depends_on:
            - kavanode
        image: "KAVA_IMAGE_TAG_REPLACED_BY_KVTOOL_HERE"
        # ports are shifted to allow access to validator & pruning node without conflicting local ports
        ports:
            # open default kava rpc port
            - "26667:26657"
            # open rest port
            - "1327:1317"
            # open grpc port
            - "9100:9090"
            # open grpc-web port
            - "9101:9091"
            # open EVM JSON-RPC port
            - "8555:8545"
            # open Eth websocket port
            - "8556:8546"
        volumes:
            - ./kava-pruning/initstate/.kava:/root/.kava
            - ./kava-pruning/shared:/docker/shared
        # start the blockchain, set rpc to listen to connections from outside the container, & set validator as peer
        command: /docker/shared/kava-entrypoint.sh
